version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: task_image
    container_name: task_container
    restart: unless-stopped
    ports:
      - "8800:8800"
    volumes:
      - ./:/var/www/html